### ISSUE TITLE
Sat

### ISSUE THREAD

**Issue by corecraftsysteme** [MicrosoftDocs/data-tools#10]
[1]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f799c393-9989-9098-cbb3-ed204415e427
* Version Independent ID: f799c393-9989-9098-cbb3-ed204415e427
* Content: [GitHub Copilot extension - Overview - Azure Data Studio](https://learn.microsoft.com/en-us/azure-data-studio/extensions/github-copilot-extension-overview)
* Content Source: [azure-data-studio/extensions/github-copilot-extension-overview.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/extensions/github-copilot-extension-overview.md)
* Service: **azure-data-studio**
* GitHub Login: @subhojit-msft
* Microsoft Alias: **subasak**

**Comment by rwestMSFT** [comment]
There does not appear to be actionable feedback here. Closing the issue.
