### ISSUE TITLE
Context of Database in the Query window "switches" back to master after executing a query on an actively selected db

### ISSUE THREAD

**Issue by itscarlo-nobnos** [MicrosoftDocs/data-tools#12]
While creating a table (following Quickstart guide), it appears that connection context automatically switches back to master, after executing a query on an actively selected db.

Expectation is that table creation should maintain current context and not return to master.

It would be easy to miss connection context while creating multiple tables, thinking they were being created in the "active" context.  So, what ends up happening is that you would have to go back and run DROP TABLE <table_name> at the master level? 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f22e0a1a-525e-7be6-c735-e6d1cf6c8110
* Version Independent ID: f22e0a1a-525e-7be6-c735-e6d1cf6c8110
* Content: [Quickstart: Connect and query SQL Server - Azure Data Studio](https://learn.microsoft.com/en-us/azure-data-studio/quickstart-sql-server)
* Content Source: [azure-data-studio/quickstart-sql-server.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/quickstart-sql-server.md)
* Service: **azure-data-studio**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by rwestMSFT** [comment]
#reassign:dlevy-msft

**Comment by rwestMSFT** [comment]
This issue has been resolved in an internal PR. Please look for the updated content in the next day or so.
