### ISSUE TITLE
How to use input parameters with SQL kernel?

### ISSUE THREAD

**Issue by frab3** [MicrosoftDocs/data-tools#13]
I came to this page looking for help on creating a parameterised Notebook to run SQL queries. Not python.
Please provide some examples how to create a SQL Notebook that uses input parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57656112-bcf3-de19-f90d-92680191e4f6
* Version Independent ID: e456625f-9be8-20e1-5933-deb31d7b80a2
* Content: [Parameterize notebooks in Azure Data Studio with the Run with Parameters action - Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/notebooks/run-with-parameters?view=sql-server-ver16)
* Content Source: [docs/azure-data-studio/notebooks/run-with-parameters.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/notebooks/run-with-parameters.md)
* Service: **azure-data-studio**
* GitHub Login: @VasuBhog
* Microsoft Alias: **vabhog**

**Comment by dlevy-msft** [comment]
Hi @frab3 - We do not currently support parameters with the SQL kernel. It is something that we have been looking at but has not made the cut. Here is a link to the issue where we are tracking this feature request: https://github.com/microsoft/azuredatastudio/issues/18709. Please feel free to add any additional thoughts there.

Thanks,

Dave

#please-close
