### ISSUE TITLE
Providing more info on setting up a Oracle databse connection

### ISSUE THREAD

**Issue by Kambaa** [MicrosoftDocs/data-tools#14]
For oracle database connections, please add some examples of valid connection configurations. Just sending user to find info about "please refer to the Oracle documentation on Data Source attribute of the ODP.NET connection string" is not enough.  A valid configuration examples and screenshots is needed. how about givin more information about an example Oracle db connection via host,port,service name or sid, with username , password? it would be much appreciated.

Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e3f95cc-e110-34ad-49bb-e5b58c8cb892
* Version Independent ID: 7e3f95cc-e110-34ad-49bb-e5b58c8cb892
* Content: [Quickstart: Connect and explore Oracle databases - Azure Data Studio](https://learn.microsoft.com/en-us/azure-data-studio/quickstart-oracle)
* Content Source: [azure-data-studio/quickstart-oracle.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/quickstart-oracle.md)
* Service: **azure-data-studio**
* GitHub Login: @tdoshin
* Microsoft Alias: **timioshin**

**Comment by dlevy-msft** [comment]
This is a great suggestion. We will add it to our backlog and prioritize it with our other updates. 

#please-close
