### ISSUE TITLE
Why not support VS proper?

### ISSUE THREAD

**Issue by gzinger** [MicrosoftDocs/data-tools#16]
It is strange that the new .sqlproj format is only available for VS-Code. Could we also use it in regular Visual Studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62e7119f-ad1a-60a2-f138-ebbb5e060a8e
* Version Independent ID: 62e7119f-ad1a-60a2-f138-ebbb5e060a8e
* Content: [Build and Publish a Project - Azure Data Studio](https://learn.microsoft.com/en-us/azure-data-studio/extensions/sql-database-project-extension-build)
* Content Source: [azure-data-studio/extensions/sql-database-project-extension-build.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/extensions/sql-database-project-extension-build.md)
* Service: **azure-data-studio**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
I see you've found the item where we're tracking this work: https://github.com/microsoft/DacFx/issues/180

There's also https://developercommunity.visualstudio.com/t/Use-new-project-file-format-for-sqlproj/480461 on the Visual Studio Dev Community.

Closing this documentation-related issue, keep tabs on the item in the DacFx repository.
#please-close
