### ISSUE TITLE
T-SQL snippet to create stored procedures in Azure Studio tutorial  results in JSON_F52E2861-18A1-11d1-8105-00805F49916B system generated column

### ISSUE THREAD

**Issue by itscarlo-nobnos** [MicrosoftDocs/data-tools#17]
After copying code from Tutorial: Use the Transact-SQL editor to create database objects - Azure Data Studio, Azure Data generates system generated column name after executing the query.

Result is in binary format. How is this readable after documentation states, 'To see formatted JSON, click the returned record."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2f54365-1b7c-f2c3-60ef-158a32b67c04
* Version Independent ID: b2f54365-1b7c-f2c3-60ef-158a32b67c04
* Content: [Use the Transact-SQL editor to create database objects - Azure Data Studio](https://learn.microsoft.com/en-us/azure-data-studio/tutorial-sql-editor)
* Content Source: [azure-data-studio/tutorial-sql-editor.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/tutorial-sql-editor.md)
* Service: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by dlevy-msft** [comment]
Hi @itscarlo-nobnos - Sorry to hear this is not working for you. Please try this again with Azure Data Studio version 1.48. It works as expected with 1.48 when I test it.

**Comment by markingmyname** [comment]
Thank you for your feedback.

We remain committed to open source, and for open-source products with open-source content repositories, you can continue to use GitHub Issues and Pull Requests like you do today. However, we are transitioning to a new feedback system for the rest of our content set. We are moving valid issues into our backlog before the GitHub Issues capability is disabled in the repository. In the case of this issue, we need to confirm that it is still valid, given that it has been open for over six months. If you want to learn more about our new feedback system, please visit aka.ms/contentuserfeedback.
