### ISSUE TITLE
Cannot download Azure Data Studio

### ISSUE THREAD

**Issue by jeremy-schaab** [MicrosoftDocs/data-tools#18]
[Enter feedback here]

I am getting a certificate expired on the download page for windows.  I am on an Azure VM so not a network issue as far as I can tell.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57d562b7-cf5a-b5dc-b485-a791a9c0f244
* Version Independent ID: 57d562b7-cf5a-b5dc-b485-a791a9c0f244
* Content: [Download and install Azure Data Studio - Azure Data Studio](https://learn.microsoft.com/en-us/azure-data-studio/download-azure-data-studio?tabs=win-install%2Cwin-user-install%2Credhat-install%2Cwindows-uninstall%2Credhat-uninstall)
* Content Source: [azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/download-azure-data-studio.md)
* Service: **azure-data-studio**
* GitHub Login: @dlevy-msft
* Microsoft Alias: **dlevy**

**Comment by kaskadz** [comment]
For me the problem is Internal Server Error:
![image](https://github.com/MicrosoftDocs/data-tools/assets/31192049/74916155-c312-4276-a0f4-67e7b70ca29d)

**Comment by lcporschen** [comment]
Same here

**Comment by dlevy-msft** [comment]
Apologies for the inconvenience! There was a configuration issue with the server that hosts our files. It has been corrected now and downloads are working as expected.

#please-close
