### ISSUE TITLE
No forum for improvements

### ISSUE THREAD

**Issue by craigs100** [MicrosoftDocs/data-tools#2]
[Enter feedback here]
Your link for giving improvements on the product takes you to a page where there is no forum for the product!

I take it from this that you don't want to improve?

I would love it if you would either take off the product update link or make it work. On Linux Mint this causes you to download a .tar.gz file when what's needed is a .deb file!

So what we ACTUALLY have to do is download the .deb file from the product installation web page, then remove product from our machines (because your deb file won't perform an in-place upgrade, we get "Error: Breaks package 'asuredatastudio' conflict: azuredatastudio ()") and then reinstall it again.

I've told you about this many times and have even participated in troubleshooting with one of your guys, a couple of years ago, but STILL you give us a system that wastes our time.

It's why I try not to use MS products if I can possibly avoid it.  Open Source developers tend to listen.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57d562b7-cf5a-b5dc-b485-a791a9c0f244
* Version Independent ID: 57d562b7-cf5a-b5dc-b485-a791a9c0f244
* Content: [Download and install Azure Data Studio - Azure Data Studio](https://learn.microsoft.com/en-us/azure-data-studio/download-azure-data-studio?tabs=win-install%2Cwin-user-install%2Credhat-install%2Cwindows-uninstall%2Credhat-uninstall)
* Content Source: [azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/download-azure-data-studio.md)
* Service: **azure-data-studio**
* GitHub Login: @dlevy-msft
* Microsoft Alias: **dlevy**

**Comment by rwestMSFT** [comment]
@craigs100 Can you please explain in clearer terms what the exact issue is? I'd be happy to help if I could understand better. Thanks.

**Comment by craigs100** [comment]
Thanks for the response. I've been through this before in minute detail over a year ago and nothing was done.

This relates to Azure Data Studio (ADS) when run on Linux Mint (Ubuntu-based).  In the top menu of ADS if you go to Help | Download Available Update and click on it, the Linux Mint File Manager opens (called Nemo) expecting to download a file called azuredatastudio-linux-1.47.0.tar.gz.  This is the first problem. Ubuntu-based systems require a .deb file.  Everyone else seems to manage to get it right, I don't see why you can't.

Once you've finally found the relevant web site and downloaded the .deb installation file (azuredatastudio-linux-1.47.0.deb) , the second problem is that it won't install without totally uninstalling Azure Data Studio first. Here is the error in the Package Manager:-

![image](https://github.com/MicrosoftDocs/data-tools/assets/1143883/a9df7161-ca04-4a07-991d-d01d461f5bc2)

Once ADS has been totally uninstalled then rerunning the .deb file re-installs ADS properly.

As I use Linux Mint as my primary desktop I obviously see a lot of 3rd party applications that get this right. GitKraken is one example, there are many others. You just click the update link, the dialogue opens, the .deb is downloaded and installed.  If they can do it, I'm sure you can ;)

Thanks.

**Comment by rwestMSFT** [comment]
Hi @craigs100

I work for the Database Docs team, so I have no record of any interactions you may have had previously. With that in mind, I'm going to chat to the Azure Data Studio team and see if we can address this. I can't and won't make any promises, but I appreciate the screenshots and explanation.

Thanks for your feedback. Since this isn't a documentation issue, I'm going to close it, but I will be tracking it internally.

**Comment by craigs100** [comment]
Because it's been so long since I submitted the issue I've gone off on the wrong foot. The update issue IS a major issue but for a different repo.  The issue here, IIRC was there is a page with a link that doesn't go where it should.  So it was a documentation issue. However, I can't remember where it was and I can't find it again. I thought what ever I clicked on to get here would have picked up it's context. Anyway, sorry for wasting your time.

**Comment by rwestMSFT** [comment]
Craig, you're not wasting anyone's time if it turns out we can help you. Let's see what the product group says about your Mint issue, and I've got a note to check forum links when I'm back on Monday, to see if there's an old link we can fix. It's par for the course here to fix old links, so your assistance to make that experience better is appreciated.

**Comment by dlevy-msft** [comment]
I am digging into this now. I found we are tracking this under this issue: https://github.com/microsoft/azuredatastudio/issues/21507. I am working on pulling together an updated status and will reply over there with any new information.
