### ISSUE TITLE
There is no feature to copy the Code cell or Text cell in Notebook in Azure Data Studio

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/data-tools#21]
Can the team add a feature to copy the Text cell or Code cell of the Notebook in Azure Data Studio? I cannot find this feature, apparently. 

![image](https://github.com/MicrosoftDocs/data-tools/assets/33271651/327b4429-d075-41f7-8463-df72b4728015)

(Note: I cannot find a place to suggest feature, so I raise it here.)

**Comment by markingmyname** [comment]
Thank you for your feedback.

We remain committed to open source, and for open-source products with open-source content repositories, you can continue to use GitHub Issues and Pull Requests like you do today. However, we are transitioning to a new feedback system for the rest of our content set. We are moving valid issues into our backlog before the GitHub Issues capability is disabled in the repository. In the case of this issue, we need to confirm that it is still valid, given that it has been open for over six months. If you want to learn more about our new feedback system, please visit aka.ms/contentuserfeedback.
