### ISSUE TITLE
Toward the past

### ISSUE THREAD

**Issue by Theshrink** [MicrosoftDocs/data-tools#22]
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/data-tools/issues/19
```

**Comment by markingmyname** [comment]
Thank you for your feedback.

We remain committed to open source, and for open-source products with open-source content repositories, you can continue to use GitHub Issues and Pull Requests like you do today. However, we are transitioning to a new feedback system for the rest of our content set. We are moving valid issues into our backlog before the GitHub Issues capability is disabled in the repository. In the case of this issue, we need to confirm that it is still valid, given that it has been open for over six months. If you want to learn more about our new feedback system, please visit aka.ms/contentuserfeedback.
