### ISSUE TITLE
MacOS "Install Azure Data Studio" not updated.

### ISSUE THREAD

**Issue by frederikspang** [MicrosoftDocs/data-tools#3]
The installation guide still mentions requirement of Rosetta for running x86 binaries (Intel Chip download link):

> For Apple Silicon users, please make sure you have Rosetta 2 installed. Some backend services are yet to be converted to native ARM64 binaries. You can run the following command in a Terminal window to install Rosetta 2.

This is no longer the case, as ARM64 (Apple Silicion), as well as an Universal build has been released - Rendering the note quoted above irrelevant.

I am happy to submit PR to resolve this, but I was unsure if this repo was syncronized from internal sources to GH, or other the way around.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57d562b7-cf5a-b5dc-b485-a791a9c0f244
* Version Independent ID: 57d562b7-cf5a-b5dc-b485-a791a9c0f244
* Content: [Download and install Azure Data Studio - Azure Data Studio](https://learn.microsoft.com/en-us/azure-data-studio/download-azure-data-studio?tabs=macOS-install%2Cwin-user-install%2Credhat-install%2Cwindows-uninstall%2Credhat-uninstall#download-azure-data-studio)
* Content Source: [azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/download-azure-data-studio.md)
* Service: **azure-data-studio**
* GitHub Login: @dlevy-msft
* Microsoft Alias: **dlevy**

**Comment by rwestMSFT** [comment]
@frederikspang Are you absolutely sure that there are no backend components that don't require Rosetta 2?

> Some backend services are yet to be converted to native ARM64 binaries.

For this reason, we will leave the article as written. Thank you for your feedback.

**Comment by frederikspang** [comment]
Hi @rwestMSFT 

You're absolutely right, and I am apparently unable to read :)

That is my bad!
