### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by walkerjian** [MicrosoftDocs/data-tools#4]
[Enter feedback here]
Not such a great tutorial experience here. Zero flow with previous tuts, and there are code problems with the json file

Incorrect type. Expected "null".
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a99a75f-f611-4496-7225-1ee32c86fa37
* Version Independent ID: 2a99a75f-f611-4496-7225-1ee32c86fa37
* Content: [Build a custom insight widget - Azure Data Studio](https://learn.microsoft.com/en-au/azure-data-studio/tutorial-build-custom-insight-sql-server)
* Content Source: [azure-data-studio/tutorial-build-custom-insight-sql-server.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/tutorial-build-custom-insight-sql-server.md)
* Service: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment]
Can you please provide some actionable feedback for us to act on this, or submit a PR with suggested changes?

**Comment by rwestMSFT** [comment]
Closing this issue, because we haven't heard back from you.
