### ISSUE TITLE
Some bits missing

### ISSUE THREAD

**Issue by walkerjian** [MicrosoftDocs/data-tools#5]
[Enter feedback here]
Some additional steps are needed, not enough details included, I had to use other techniques to backup and restore database. Could confuse and discourage a noob

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: baf1cda0-bc34-df67-057e-f3097741bd1a
* Version Independent ID: baf1cda0-bc34-df67-057e-f3097741bd1a
* Content: [Back up and restore a database - Azure Data Studio](https://learn.microsoft.com/en-au/azure-data-studio/tutorial-backup-restore-sql-server)
* Content Source: [azure-data-studio/tutorial-backup-restore-sql-server.md](https://github.com/MicrosoftDocs/data-tools/blob/main/azure-data-studio/tutorial-backup-restore-sql-server.md)
* Service: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment]
@walkerjian I cannot see any issue with the article. Can you provide more information about what you think is missing?

**Comment by walkerjian** [comment]
This is a time ago now... I will go back to the front and do it again, and see if I can reproduce the embuggerances.

**Comment by rwestMSFT** [comment]
As a Terry Pratchett fan with his biography on my desk as I write this, I hope we can help you resolve any issues you've discovered.

**Comment by markingmyname** [comment]
@walkerjian 

Please let us know some of the additional techniques and suggestions you tried to be successful with this task.  We will add this notion to our backlog. Thank you.

**Comment by markingmyname** [comment]
We remain committed to open source, and for open-source products with open-source content repositories, you can continue to use GitHub Issues and Pull Requests like you do today. However, we are transitioning to a new feedback system for the rest of our content set. We are moving valid issues into our backlog before the GitHub Issues capability is disabled in the repository. In the case of this issue, we need to confirm that it is still valid, given that it has been open for over six months. If you want to learn more about our new feedback system, please visit aka.ms/contentuserfeedback.

**Comment by walkerjian** [comment]
Sorry, that is getting to be a bit too long ago! can’t remember - I would have to redo from start and don’t have the time, cheers ...
